server:
  contextPath: /
  port: 8088
#spring:
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#  freemarker:
#    cache: false
#  thymeleaf:
#    cache: false

spring:
  redis:
    host: localhost
    password:
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

logging:
  level:
    com.websocket.edu: debug
    